import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    category: 'HERRAMIENTAS MANUALES',
    name: 'Pinza de Fuerza',
    brand: 'STANLEY',
    supplier: 'INDUMA S.A.',
    price: 1259.19,
    stock: 3,
    status: 'low',
  },
  {
    id: '2',
    category: 'ELECTRICIDAD',
    name: 'Cable Unipolar 2.5mm',
    brand: 'PRYSMIAN',
    supplier: 'COBREX',
    price: 845.50,
    stock: 42,
    status: 'normal',
  },
  {
    id: '3',
    category: 'SEGURIDAD',
    name: 'Candado Bronce 40mm',
    brand: 'ACETRA',
    supplier: 'GLOBAL LOCKS',
    price: 2430.00,
    stock: 0,
    status: 'out',
  },
  {
    id: '4',
    category: 'PINTURERÍA',
    name: 'Pincel Profesional Nro 20',
    brand: 'EL GALGO',
    supplier: 'PINTAR S.A.',
    price: 3120.45,
    stock: 15,
    status: 'normal',
  },
  {
    id: '5',
    category: 'CONSTRUCCIÓN',
    name: 'Cinta Métrica 5m',
    brand: 'BREMEN',
    supplier: 'HERRAMAX',
    price: 5670.00,
    stock: 1,
    status: 'low',
  },
  {
    id: '6',
    category: 'BULONERÍA',
    name: 'Tornillo Madera 2" (x100)',
    brand: 'FIX-PRO',
    supplier: 'BULONES NORTE',
    price: 412.20,
    stock: 120,
    status: 'normal',
  },
];
